name: terradem

channels:
        - conda-forge

dependencies:
        - python>=3
        - pip
        - scipy
        - matplotlib
        - tqdm
        - geopandas
        - opencv
        - git
        - pytest
        - pytransform3d
        - geoutils
        - richdem
        - scikit-image
        - cartopy
        - requests
        - graphviz
        # xdem should be installed, but is currently installed from source instead.
          #- xdem
        - pip:
            - glacier_lengths
            - "git+https://github.com/dugalh/simple_ortho.git"


        # For developing
        - pre-commit
