name: terradem

channels:
        - conda-forge

dependencies:
        - python>=3
        - pip
        - scipy
        - matplotlib
        - tqdm
        - geopandas
        - opencv
        - git
        - pytest
        - pip:
                - pytransform3d
                - https://github.com/GlacioHack/GeoUtils/tarball/master
                - https://github.com/GlacioHack/xdem/tarball/main


