name: terradem

channels:
        - conda-forge

dependencies:
        - python>=3
        - pip
        - scipy
        - matplotlib
        - tqdm
        - geopandas
        - opencv
        - git
        - pytest
        - pytransform3d
        - geoutils
        - richdem
          #- xdem

        # For developing
        - pre-commit
